### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by danlutz**
I almost finished the german translation, it will be proofread by a german teacher tomorrow and there are some uncertainties:

- `secure_tezos_wallet`: Need explanation of context of operation
- `secure_your_tezbox`: Need explanation of context of operation
- `details_dont_match`: What does details mean here?
- `level`: Need explanation of context
- `clear`: Need explanation of context of operation
- `import_kt1_account_msg`: Meaning of sentence 'You can view all of your originated KT1 addresses on'
- `operation_failed2`: Meaning of inputs in this sentence

If you could provide some explanation for these keys in the json file I can finish the translation 👍

### CODE REVIEW

**Comment by stephenandrews** [comment]
- `secure_tezos_wallet`: This is the tezbox slogal - TezBox - Secure Tezos Wallet
- `secure_your_tezbox`: This is the title for the page where users enter an encryption password to added encrypt and secure their tezbox data
- `details_dont_match`: When creating a new wallet, you need to re-enter the seed and passphrase to ensure you have copied them correctly. If the details that are re-entered do not match, this message is displayed
- `level`: The block level of the tezos blockchain
- `clear`: This is the button displayed on the send page, which clears all the fields back to their default state
- `import_kt1_account_msg`: After the sentence, a link to tzscan.io is provided.
- `operation_failed2`: Inputs refer to the fields used for the Send transaction - e.g. to address, amount, fee, parameters etc

**Comment by danlutz** [comment]
Thanks for the quick answer, I just updated the respecting fields 👍 
Like I said, the translation will be proof-read by a german teacher today, I will let you know when the final version is approved!

**Comment by danlutz** [comment]
Updated again after proofreading with the teacher - should be OK now!

Important Note: On line 172, $$ needs to be replaced with the tzscan link. In english you can just append it after the string, in german you need to add a additional word after it so it makes sense :)

Though: Sometimes tezzies are referred to as 'tez', sometimes as 'XTZ'. Should we agree on a single abbreviation to make things more clear for our users?

Glad to contribute to this great project, keep up the awesome work 💯

**Comment by oliversimon** [comment]
Hi danlutz, another fellow who had started to translate to German chiming in. Regarding "import_kt_address_info" on line 192, I'd like to suggest something along the lines of: "Wir haben $$ mit Ihrem Konto verknüpfte KT1-Adresse(n) gefunden (...)" or "Wir haben $$ mit Ihrem Account in Zusammenhang stehende KT1-Adresse(n) gefunden (...)". The current version "Wir haben $$ KT1-Adresse(n) gefunden die mit Ihrem Public Key verknüpft sind (...)" seems to be a little problematic because in case there's only one address found, the sentence would be grammatically incorrect. What do you think?

**Comment by danlutz** [comment]
Good point, I will update the pull request!

**Comment by danlutz** [comment]
I renamed "Konto" to "Account" to have it named the same way throughout the app 👍

**Comment by stephenandrews** [comment]
Thanks guys :-)

**Pull request merged**
